export const MESSAGE = {
    USER_MESSAGES: {
        EMAIL_REGISTER: "Your email registerd successfully",
        ADD: "registerd successfully",
        UPDATE: "record updated successfully",
        UPDATE_FAILED: "Record not updated!",
        DELETE: "record deleted successfully",
        REGISTRATION_FAILED: "Registration failed!",
        LOGIN: "Login successfully",
        LOGIN_FAILED: "Login failed",
        LOGOUT: "Logout Successfully",
        CHANGE_PASSWORD: "Your password updated successfully",
        INCORRECT_PASSWORD: "Your password is incorrect",
        EMAIL_ALREADY_EXISTED: "Email is already registered!",
        INVALID_EMAILID: 'Please enter valid email',
        PASSWORD_MISMATCH: '<PASSWORD>',
        NO_RECORDS_FOUND: 'No records found!',
        RECORD_FOUND: "All records are here",
        SINGLE_RECORD_FOUND: "your record is here",
        INVALID_CREDENTIAL: "Please provide valid credential",
        SUBJECT_INSERT: "Subject created successfully",
        SUBJECT_UPDATE: "Subject Updated Successfully",
        SUBJECT_DELETE: "Subject Deleted Successfully",
        SUBJECT_ERROR: "Error occur while creating subject",
        SYLLABUS_INSERTED: "Syllabus inserted successfully",
        SYLLABUS_UPDATED: "Syllabus Updated Successfully",
        SYLLABUS_DELETED: "Syllabus Deleted Successfully",
        SYLLABUS_ERROR: "Error Occur While Creating syllabus",
        QUESTION_CREATE: "Questions created successfully",
        QUESTION_UPDATE: "Question Update Successfullly",
        QUESTION_DELETE: "Question Delete Successfullly",
        QUESTION_ERROR: "Error Occur While creating questions!",
        TEST_GENERATE: "Test generated successfully",
        ANSWERS_SUBMITTED:"Answers Submitted Successfully",
        ANSWER_SUBMISSION_ERROR: "Answers Not Submitted!",
        QUESTION_POSTED: "Your question posted successfully",
        QUESTION_POSTED_ERROR: "Error occurred while posting your question!",
    },

    SERVER_MESSAGE: {
        GENERIC_ERROR: 'Something went wrong!',
        NOT_AUTHORIZED: 'You are not authorized to perform this action!',
        ALREADY_REGISTERD: 'User Already Registered!',
        EXPIRED_TOKEN: '<PASSWORD>!',
        TOKEN_NOT_PROVIDED: 'Token Not Provided!',
        UNAUTHORIZED: 'Unauthorized!',
        FORBIDDEN: 'Forbidden!',
        INTERNAL_SERVER_ERROR: 'Internal Server Error!',
        BAD_REQUEST: 'Bad Request!',
    }
}